### ISSUE TITLE
NilClassによるundefined method エラー

### ISSUE THREAD

**Issue by kaho211** [kaho211/practice#1]
```
Main.rb:35:in `proc': undefined method `+' for nil:NilClass (NoMethodError)

      p path[0] + " => " + @data[path[0]].to_s
                ^
	from Main.rb:46:in `<main>'
```

これは、path[0]がnilであるため、“＋”の処理はできない、というエラーである。

**Comment by kaho211** [comment]
正しい出力は「bsd」であるが、実際は「nil」となっている。この出力をしている箇所は「p path[0] + " => " + @data[path[0]].to_s」である。
